# Generated by Django 2.2.1 on 2019-05-19 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='System', max_length=100)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='System', max_length=100)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_show', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             to='pyindex.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=2000)),
                ('icon', models.CharField(max_length=2000)),
                ('keyword', models.CharField(max_length=10)),
                ('tags', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='System', max_length=100)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='System', max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyindex.Category')),
            ],
        ),
    ]
